import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
           <Link href="/dashboard" >Dashboard</Link>
           <Link href="/dashboard/settings" >Settings</Link>
           <Link href="/user" >user</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
